enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
dpi = "120-640dpi"

[GooglePhotos]
build-mode = "both"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitter]
patches-source = "crimera/piko-newx"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
version = "latest"
included-patches = "'NewX: Restore Twitter branding'"

# Wagg13 Tinder patch unlocks Unlimited Rewind only.
[Tinder-Wagg13]
app-name = "Tinder"
pkg-name = "com.tinder"
patches-source = "WaggBR/Wagg13Patch_Morphe"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Wagg13"
version = "17.34.1"
build-mode = "both"
arch = "arm64-v8a"
dpi = "480-640dpi"
direct-dlurl = "https://github.com/Othmane-ElAlami/Stock-APKs/releases/download/v1/com.tinder-17.34.1-arm64-v8a.apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tinder/tinder-tinder/"


[Music]
enabled = false
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube]
enabled = false
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
